apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  install:
    crds: Skip          # ← Skippa CRDs vid install
  upgrade:
    crds: Skip          # ← Skippa CRDs vid upgrade
  chart:
    spec:
      chart: traefik
      version: "34.*"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    entryPoints:
      web:
        address: ":80"
    providers:
      kubernetesGateway:
        enabled: true
    gateway:
      namespacePolicy: All
      enabled: true
      name: traefik-gateway
      listeners:
        web:
          port: 8080
          protocol: HTTP
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/azure-dns-label-name: flux-demo